package com.soft.application.model;
/*
 * Role.java
 *
 * Generated with Matisse Schema Definition Language 9.1.10
 * Generation date: Sun Mar 18 18:46:52 2018
 */

// Note: the package and extends declarations are generated by mt_sdl, do not modify them

import com.matisse.reflect.*;

/**
 * <code>Role</code> is a schema class generated by <code>mt_sdl</code>.
 * Any user-written classes will be found at the end of the file, after
 * the '// END of Matisse SDL Generated Code' comment.
 * Attribute types, default values, and relationship minimum and maximum
 * cardinality are stored in the database itself, not in this source code.
 * For more information, see <i>Getting Started with MATISSE</i>.
 */
public class Role extends com.matisse.reflect.MtObject {

    // BEGIN Matisse SDL Generated Code
    // DO NOT MODIFY UNTIL THE 'END of Matisse SDL Generated Code' MARK BELOW
    /*
     * Generated with Matisse Schema Definition Language 9.1.10
     * Generation Date: Sun Mar 18 18:46:52 2018
     */

    /*
     * Class variables and methods
     */

    /** Class <code>Role</code> cache ID */
    private static int CID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtClass.Loader("Role"));

    /**
     * Gets the <code>Role</code> class descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a class descriptor
     */
    public static com.matisse.reflect.MtClass getClass(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtClass)db.getCachedObject(CID);
    }

    /**
     * Factory constructor. This constructor is called by <code>MtObjectFactory</code>.
     * It is public for technical reasons but is not intended to be called
     * directly by user methods.
     * @param db a database
     * @param mtOid an existing object ID in the database
     */
    public Role(com.matisse.MtDatabase db, int mtOid)  {
        super(db, mtOid);
    }

    /**
     * Cascaded constructor, used by subclasses to create a new object in the database.
     * It is protected for technical reasons but is not intended to be called
     * directly by user methods.
     * @param mtCls a class descriptor (the class to instantiate)
     */
    protected Role(com.matisse.reflect.MtClass mtCls)  {
        super(mtCls);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>instanceIterator(Role.class);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>instanceIterator(numObjPerBuffer, Role.class);
    }

    /**
     * Counts the number of instances of this class (and its subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getInstanceNumber();
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>ownInstanceIterator(Role.class);
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>ownInstanceIterator(numObjPerBuffer, Role.class);
    }

    /**
     * Counts the number of own instances of this class (excluding subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getOwnInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getOwnInstanceNumber();
    }

    /*
     * Attribute access methods
     */

    /* Attribute 'roleId' */

    /** Attribute <code>roleId</code> cache ID */
    private static int roleIdCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("roleId",CID));

    /**
     * Gets the <code>roleId</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getRoleIdAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(roleIdCID);
    }


    /**
     * Gets the <code>roleId</code> attribute value.
     * @return the value
     *
     * @see #setRoleId
     * @see #removeRoleId
     */
    public final int getRoleId() {
        return getInteger(getRoleIdAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>roleId</code> attribute value.
     * @param val the new value
     *
     * @see #getRoleId
     * @see #removeRoleId
     */
    public final void setRoleId(int val) {
        setInteger(getRoleIdAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>roleId</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getRoleId
     * @see #setRoleId
     */
    public final void removeRoleId() {
        removeValue(getRoleIdAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getRoleId
     * @see #setRoleId
     */
    public final boolean isRoleIdDefaultValue() {
        return isDefaultValue(getRoleIdAttribute(getMtDatabase()));
    }


    /* Attribute 'roleName' */

    /** Attribute <code>roleName</code> cache ID */
    private static int roleNameCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("roleName",CID));

    /**
     * Gets the <code>roleName</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getRoleNameAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(roleNameCID);
    }


    /**
     * Gets the <code>roleName</code> attribute value.
     * @return the value
     *
     * @see #setRoleName
     * @see #removeRoleName
     */
    public final String getRoleName() {
        return getString(getRoleNameAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>roleName</code> attribute value.
     * @param val the new value
     *
     * @see #getRoleName
     * @see #removeRoleName
     */
    public final void setRoleName(String val) {
        setString(getRoleNameAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>roleName</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getRoleName
     * @see #setRoleName
     */
    public final void removeRoleName() {
        removeValue(getRoleNameAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getRoleName
     * @see #setRoleName
     */
    public final boolean isRoleNameDefaultValue() {
        return isDefaultValue(getRoleNameAttribute(getMtDatabase()));
    }


    /*
     * Relationship access methods
     */

    /* Relationship 'isAssigned' */

    /** Relationship <code>isAssigned</code> cache ID */
    private static int isAssignedCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtRelationship.Loader("isAssigned",CID));

    /**
     * Gets the <code>isAssigned</code> relationship descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a relationship descriptor object
     */
    public static com.matisse.reflect.MtRelationship getIsAssignedRelationship(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtRelationship)db.getCachedObject(isAssignedCID);
    }

    /**
     * Gets the <code>isAssigned</code> relationship's successors.
     * @return an array of objects
     *
     * @see #getIsAssignedSize
     * @see #isAssignedIterator
     * @see #setIsAssigned
     * @see #removeIsAssigned
     */
    public final User[] getIsAssigned() {
        return (User[])getSuccessors(getIsAssignedRelationship(getMtDatabase()), User.class);
    }

    /**
     * Counts the <code>isAssigned</code> relationship's successors.
     * @return the number of successors
     *
     * @see #getIsAssigned
     * @see #isAssignedIterator
     * @see #setIsAssigned
     * @see #removeIsAssigned
     */
    public final int getIsAssignedSize() {
        return getSuccessorSize(getIsAssignedRelationship(getMtDatabase()));
    }

    /**
     * Opens an iterator on the <code>isAssigned</code> relationship's successors.
     * @param <E> a MtObject class     * @return an object iterator
     *
     * @see #getIsAssigned
     * @see #getIsAssignedSize
     * @see #setIsAssigned
     * @see #removeIsAssigned
     */
    public final <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> isAssignedIterator() {
        return this.<E>successorIterator(getIsAssignedRelationship(getMtDatabase()), User.class);
    }

    /**
     * Sets the <code>isAssigned</code> relationship's successors.
     * @param succs an array of objects
     *
     * @see #getIsAssigned
     * @see #getIsAssignedSize
     * @see #isAssignedIterator
     * @see #removeIsAssigned
     */
    public final void setIsAssigned(User[] succs) {
        setSuccessors(getIsAssignedRelationship(getMtDatabase()), succs);
    }

    /**
     * Inserts one object at the beginning of the existing <code>isAssigned</code> successors list.
     * @param succ the object to add
     *
     * @see #getIsAssigned
     * @see #getIsAssignedSize
     * @see #isAssignedIterator
     * @see #setIsAssigned
     * @see #removeIsAssigned
     */
    public final void prependIsAssigned(User succ) {
        prependSuccessor(getIsAssignedRelationship(getMtDatabase()), succ);
    }

    /**
     * Adds one object to the end of the existing <code>isAssigned</code> successors list.
     * @param succ the object to add
     *
     * @see #getIsAssigned
     * @see #setIsAssigned
     * @see #removeIsAssigned
     * @see #getIsAssignedSize
     * @see #isAssignedIterator
     */
    public final void appendIsAssigned(User succ) {
        appendSuccessor(getIsAssignedRelationship(getMtDatabase()), succ);
    }
    /** Adds multiple objects to the end of the existing <code>isAssigned</code> successors list.
     * @param succs an array of objects to add
     *
     * @see #getIsAssigned
     * @see #setIsAssigned
     * @see #removeIsAssigned
     * @see #getIsAssignedSize
     * @see #isAssignedIterator
     */
    public final void appendIsAssigned(User[] succs) {
        addSuccessors(getIsAssignedRelationship(getMtDatabase()), succs);
    }

    /**
     * Removes objects from the <code>isAssigned</code> successors list.
     * @param succs an array of objects to remove
     *
     * @see #getIsAssigned
     * @see #setIsAssigned
     * @see #getIsAssignedSize
     * @see #isAssignedIterator
     */
    public void removeIsAssigned(User[] succs) {
        removeSuccessors(getIsAssignedRelationship(getMtDatabase()), succs);
    }

    /**
     * Removes one object from the <code>isAssigned</code> successors list.
     * @param succ the object to remove
     *
     * @see #getIsAssigned
     * @see #setIsAssigned
     * @see #getIsAssignedSize
     * @see #isAssignedIterator
     */
    public void removeIsAssigned(User succ) {
        removeSuccessor(getIsAssignedRelationship(getMtDatabase()), succ);
    }

    /**
     * Removes all <code>isAssigned</code> successors.  When the minimum cardinality
     * is 1, a new successor must be set before commit.
     */
    public final void clearIsAssigned() {
        clearSuccessors(getIsAssignedRelationship(getMtDatabase()));
    }


    // END of Matisse SDL Generated Code

    /*
     * You may add your own code here...
     */

    /**
     * Default constructor provided as an example.
     * You may delete this constructor or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @param db a database
     */
    public Role(com.matisse.MtDatabase db) {
        super(getClass(db));
    }

    /**
     * Example of <code>toString</code> method.
     * You may delete this method or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @return a string
     */
    public java.lang.String toString() {
        return super.toString() + "[Role]";
    }
}
